# Generated by Django 3.2.13 on 2022-09-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='logos/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='LogoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(null=True, upload_to='results/')),
                ('stamp', models.TextField()),
                ('thres', models.FloatField()),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo.logo')),
            ],
        ),
    ]
