# Generated by Django 3.2.13 on 2022-07-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='uploader',
        ),
    ]
