# Generated by Django 3.2.13 on 2022-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_remove_logo_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
